/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wipdev.LwJGLEngine;

import com.wipdev.LwJGLEngine.Engine.Engine;

import java.io.IOException;

public class App {

    public static void main(String[] args){
        try {
            Settings.load(Settings.DEFAULT_FILE_PATH);
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println(Settings.asString());

        Engine engine = new Engine();
        engine.run();



    }
}
